version: '3.8'

services:
  app:
    build:
      context: ./applifting-backend
      dockerfile: .Dockerfile  # Fixed to point to the correct Dockerfile name
    ports:
      - '4000:4000'  # HTTP port for development
      - '4001:4001'  # WebSocket port for development
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_HOST: db # Override value from .env.development file to run db in a container
    env_file:
      - ./applifting-backend/.env.development

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: applifting
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
